name: egyptian-id-ocr
services:
  - name: api
    source_dir: /
    github:
      repo: YOUR_USERNAME/OCR_Egyptian_ID
      branch: main
    run_command: python microservice.py
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8000
    health_check:
      http_path: /health
    routes:
      - path: /
    envs:
      - key: PORT
        value: "8000"
      - key: PYTHONUNBUFFERED
        value: "1"
